export const updatedResume = {
  basics: {
    name: "KRISHNAMRAJU KAMMILI",
    headline: "Full Stack Developer & DevOps Engineer",
    email: "pradeepthipradeepthi4@gmail.com",
    phone: "469-569-6257",
    location: "",
    url: {
      label: "",
      href: "",
    },
    customFields: [],
    picture: {
      url: "https://i.imgur.com/fTmUbG2.jpeg",
      size: 64,
      aspectRatio: 0.75,
      borderRadius: 0,
      effects: {
        hidden: false,
        border: false,
        grayscale: false,
      },
    },
  },
  sections: {
    summary: {
      name: "Summary",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "summary",
      content:
        "Accomplished Full Stack Developer and DevOps Engineer with 7-8 years of experience in dynamic environments. credited for consistent productivity and effective issue resolution. Working in Fidelity",
    },
    awards: {
      name: "Awards",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "awards",
      items: [],
    },
    certifications: {
      name: "Certifications",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "certifications",
      items: [],
    },
    education: {
      name: "Education",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "education",
      items: [
        {
          id: "t45dbgvt8rkhorn43iw5e8fx",
          visible: true,
          institution: "University of Illinois at Springfield, IL",
          studyType: "Master of Science in Computer Science",
          area: "Computer Science",
          score: "",
          date: "2015-09-01 - 2019-06-01",
          summary: "",
          url: {
            label: "",
            href: "",
          },
        },
      ],
    },
    experience: {
      name: "Experience",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "experience",
      items: [
        {
          id: "un8x72bh3q9y46wzub56zkws",
          visible: true,
          company: "Walmart",
          position: "SR Front End Developer",
          location: "",
          date: "2023-05-01 - undefined",
          summary:
            "<p>Involved in modernizing and enhancing legacy systems, including PSW and NBDB, by migrating them to Edithub using newer technologies like Angular 18. Played a key role in addressing production issues and developing new features to improve user experience.</p><ul><li><p>This is my first point</p></li><li><p>This is my second point</p></li><li><p>This is my third point.</p></li></ul>",
          url: {
            label: "",
            href: "",
          },
        },
        {
          id: "ps35njrcyafttf92z8lr2qp3",
          visible: true,
          company: "Lumen",
          position: "Developer",
          location: "",
          date: "2021-10-01 - 2023-05-01",
          summary:
            "<p>Led the development of a self-service portal, Dycon, which allowed customers to manage connectivity options across multiple cloud providers—the project aimed to streamline the user experience and enhance global availability, resulting in significant cost savings.</p><p></p><p>hello hello</p>",
          url: {
            label: "",
            href: "",
          },
        },
        {
          id: "zikmgmsa2cik1725636byau2",
          visible: true,
          company: "Verizon",
          position: "Full Stack Developer (React, Node)",
          location: "",
          date: "2019-12-01 - 2021-09-02",
          summary:
            "Developed critical tools and applications for Verizon's network and customer relationship management. The VSON project focused on adjusting bandwidth and managing network infrastructure, while the CRM system streamlined lead tracking and customer interactions.",
          url: {
            label: "",
            href: "",
          },
        },
        {
          id: "j7qlumpy500k8lr23agq8hpd",
          visible: true,
          company: "Pluto TV",
          position: "Front End Developer (React, Vue)",
          location: "",
          date: "2018-05-01 - 2019-12-01",
          summary:
            "Contributed to the development of Pluto TV, a cross-platform streaming service offering free TV channels. The project involved optimizing the user experience across multiple platforms and integrating accessibility features to enhance inclusivity.",
          url: {
            label: "",
            href: "",
          },
        },
        {
          id: "uetddhzwq7gcqr67k9ov0hel",
          visible: true,
          company: "Capital One",
          position: "Software Engineer",
          location: "",
          date: "2017-12-01 - 2018-05-01",
          summary:
            "Developed tools to improve authentication processes and security at Capital One. The project included implementing multi-factor authentication, document verification, and fraud detection tools to secure customer interactions.",
          url: {
            label: "",
            href: "",
          },
        },
      ],
    },
    volunteer: {
      name: "Volunteering",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "volunteer",
      items: [],
    },
    interests: {
      name: "Interests",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "interests",
      items: [],
    },
    languages: {
      name: "Languages",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "languages",
      items: [],
    },
    profiles: {
      name: "Profiles",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "profiles",
      items: [
        {
          id: "bag82jsb5e3z6olfii0prlwv",
          visible: true,
          network: "GitHub",
          username: "kkammili",
          icon: "github",
          url: {
            label: "",
            href: "https://github.com/kkammili",
          },
        },
        {
          id: "kj6wt5h9xne7jysi15hrsvi9",
          visible: true,
          network: "Portfolio",
          username: "kkammili.com",
          icon: "portfolio",
          url: {
            label: "",
            href: "https://kkammili.com/",
          },
        },
      ],
    },
    projects: {
      name: "Projects",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "projects",
      items: [],
    },
    publications: {
      name: "Publications",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "publications",
      items: [],
    },
    references: {
      name: "References",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "references",
      items: [],
    },
    skills: {
      name: "Skills",
      columns: 1,
      separateLinks: true,
      visible: true,
      id: "skills",
      items: [
        {
          id: "i0c6fozw1mbbo97tpch475df",
          visible: true,
          name: "Frontend Technologies",
          description: "",
          level: 5,
          keywords: [
            "React.js (Redux, Redux Thunk, Redux Saga, Redux Toolkit, React Router), Vue.js (Vuex), Angular (NgRx, Signal Store), Nx Monorepo, JavaScript (ES6+), HTML5, CSS3",
            "HTML",
            "CSS",
            "Radix UI",
            "ShadCn",
            "Angular2+",
            "JavaScript",
          ],
        },
        {
          id: "b7nntr21u4bhuzkocwl81oa6",
          visible: true,
          name: "Frontend Testing",
          description: "",
          level: 5,
          keywords: ["Enzyme", "Cypress", "Mocha", "Chai", "Jest", "Jasmine", "Cucumber", "Karma"],
        },
        {
          id: "uxcqtl4ev9swoa0cgc34rw34",
          visible: true,
          name: "Backend Technologies",
          description: "",
          level: 5,
          keywords: [
            "Node.js (Express, Nest), Java (Spring Boot), MongoDB, MySQL, PostgreSQL, RESTful APIs, JWT Authentication, Swagger, Postman, Insomnia, GraphQL",
            "Express.js",
          ],
        },
        {
          id: "stouyzbpnelrxwrcmxihw4pr",
          visible: true,
          name: "DevOps & Tools",
          description: "",
          level: 5,
          keywords: [
            "AWS (EC2, Lambda, Elastic Beanstalk, Amplify, S3, RDS, DynamoDB, VPC, Route 53, CloudFormation, CloudWatch), Docker, Jenkins, Shell Scripting, Vim, WebStorm",
            "Git",
           ],
        },
      ],
    },
    custom: {},
  },
  metadata: {
    template: "ditto",
    layout: [
      [
        ["profiles", "summary", "experience", "education", "projects", "volunteer", "references"],
        ["skills", "interests", "certifications", "awards", "publications", "languages"],
      ],
    ],
    css: {
      value: "* {\n\toutline: 1px solid #000;\n\toutline-offset: 4px;\n}",
      visible: false,
    },
    page: {
      margin: 26,
      format: "a4",
      options: {
        breakLine: false,
        pageNumbers: true,
      },
    },
    theme: {
      background: "#ffffff",
      text: "#000000",
      primary: "#65a30d",
    },
    typography: {
      font: {
        family: "IBM Plex Serif",
        subset: "latin",
        variants: ["regular", "italic", "600"],
        size: 14,
      },
      lineHeight: 1.5,
      hideIcons: false,
      underlineLinks: true,
    },
    notes: "",
  },
};
